### ISSUE TITLE
Homebrew installation error

### ISSUE THREAD

**Issue by odysseus0** [iterative/homebrew-dvc#12] opened 2019-04-11 02:19 UTC
```
(base) ➜  ~ brew install iterative/homebrew-dvc/dvc
==> Tapping iterative/dvc
Cloning into '/usr/local/Homebrew/Library/Taps/iterative/homebrew-dvc'...
remote: Enumerating objects: 9, done.
remote: Counting objects: 100% (9/9), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 9 (delta 0), reused 1 (delta 0), pack-reused 0
Unpacking objects: 100% (9/9), done.
Tapped 1 cask and 1 formula (37 files, 43.3KB).
==> Installing dvc from iterative/dvc
==> Downloading https://github.com/iterative/dvc/archive/0.35.6.tar.gz
==> Downloading from https://codeload.github.com/iterative/dvc/tar.gz/0.35.6
######################################################################## 100.0%
Warning: Cannot verify integrity of adb8a1dfac5ec473d5e82da64a7b3805aa37cd60cf9361c9e0cad7bd1683e6cf--dvc-0.35.6.tar.gz
A checksum was not provided for this resource
For your reference the SHA256 is: 06c46fa7418a719850cfaec2369dc48f0b2fb7f6ecc995c7b24b6db46a52b2f3
==> Downloading https://files.pythonhosted.org/packages/37/db/89d6b043b22052109da35416abc3c397655e4bd3cff031446ba02b9654fa/virtualenv-16.4.3.tar.gz
######################################################################## 100.0%
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/dvc--homebrew-virtualenv-20190411-7172-10n8jmm/target --install-scripts=/private/tmp/dvc--homebrew-virtualenv-20190411-7172-10n8jmm/target/bin --single-version-externally-managed --record=insta
==> python -s /private/tmp/dvc--homebrew-virtualenv-20190411-7172-10n8jmm/target/bin/virtualenv -p python /usr/local/Cellar/dvc/0.35.6/libexec
Last 15 lines from /Users/georgezhang/Library/Logs/Homebrew/dvc/02.python:
2019-04-11 10:15:24 +0800

python
-s
/private/tmp/dvc--homebrew-virtualenv-20190411-7172-10n8jmm/target/bin/virtualenv
-p
python
/usr/local/Cellar/dvc/0.35.6/libexec

python: can't open file '/private/tmp/dvc--homebrew-virtualenv-20190411-7172-10n8jmm/target/bin/virtualenv': [Errno 2] No such file or directory
```

**Comment by odysseus0** [comment] 2019-04-11 15:10
➜  ~ brew install iterative/homebrew-dvc/dvc
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).

==> Installing dvc from iterative/dvc
==> Downloading https://github.com/iterative/dvc/archive/0.35.6.tar.gz
Already downloaded: /Users/georgezhang/Library/Caches/Homebrew/downloads/adb8a1dfac5ec473d5e82da64a7b3805aa37cd60cf9361c9e0cad7bd1683e6cf--dvc-0.35.6.tar.gz
Warning: Cannot verify integrity of adb8a1dfac5ec473d5e82da64a7b3805aa37cd60cf9361c9e0cad7bd1683e6cf--dvc-0.35.6.tar.gz
A checksum was not provided for this resource
For your reference the SHA256 is: 06c46fa7418a719850cfaec2369dc48f0b2fb7f6ecc995c7b24b6db46a52b2f3
==> Downloading https://files.pythonhosted.org/packages/37/db/89d6b043b22052109da35416abc3c397655e4bd3cff031446ba02b9654fa/virtualenv-1
Already downloaded: /Users/georgezhang/Library/Caches/Homebrew/downloads/5ef64a64cc03693fde53fa854689f38961d1645c648e8a47d4235e714a07e04d--virtualenv-16.4.3.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target -
==> python -s /private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target/bin/virtualenv -p python /usr/local/Cellar/dvc/0.35.6
Last 15 lines from /Users/georgezhang/Library/Logs/Homebrew/dvc/02.python:
2019-04-11 23:02:43 +0800

python
-s
/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target/bin/virtualenv
-p
python
/usr/local/Cellar/dvc/0.35.6/libexec

python: can't open file '/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target/bin/virtualenv': [Errno 2] No such file or directory

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/iterative/homebrew-dvc/issues

**Comment by odysseus0** [comment] 2019-04-11 15:11
➜  ~ brew install iterative/homebrew-dvc/dvc
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).

==> Installing dvc from iterative/dvc
==> Downloading https://github.com/iterative/dvc/archive/0.35.6.tar.gz
Already downloaded: /Users/georgezhang/Library/Caches/Homebrew/downloads/adb8a1dfac5ec473d5e82da64a7b3805aa37cd60cf9361c9e0cad7bd1683e6cf--dvc-0.35.6.tar.gz
Warning: Cannot verify integrity of adb8a1dfac5ec473d5e82da64a7b3805aa37cd60cf9361c9e0cad7bd1683e6cf--dvc-0.35.6.tar.gz
A checksum was not provided for this resource
For your reference the SHA256 is: 06c46fa7418a719850cfaec2369dc48f0b2fb7f6ecc995c7b24b6db46a52b2f3
==> Downloading https://files.pythonhosted.org/packages/37/db/89d6b043b22052109da35416abc3c397655e4bd3cff031446ba02b9654fa/virtualenv-1
Already downloaded: /Users/georgezhang/Library/Caches/Homebrew/downloads/5ef64a64cc03693fde53fa854689f38961d1645c648e8a47d4235e714a07e04d--virtualenv-16.4.3.tar.gz
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target -
==> python -s /private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target/bin/virtualenv -p python /usr/local/Cellar/dvc/0.35.6
Last 15 lines from /Users/georgezhang/Library/Logs/Homebrew/dvc/02.python:
2019-04-11 23:02:43 +0800

python
-s
/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target/bin/virtualenv
-p
python
/usr/local/Cellar/dvc/0.35.6/libexec

python: can't open file '/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target/bin/virtualenv': [Errno 2] No such file or directory

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/iterative/homebrew-dvc/issues

**Comment by odysseus0** [comment] 2019-04-11 15:14
Not sure if it will be any useful information, but I used z-shell with oh-my-zsh.

**Comment by odysseus0** [comment] 2019-04-11 15:15
Ah, same thing happened even when I ran it with bash.

**Comment by odysseus0** [comment] 2019-04-11 15:15
Ah, same thing happened even when I ran it with bash.

**Comment by efiop** [comment] 2019-04-11 18:31
@odysseus0 yeah, but have you left virtualenv though? That `(base)` suffix indicates that you are inside of a virtualenv, unless I'm missing something.

**Comment by odysseus0** [comment] 2019-04-12 02:07
Yes, I did for the second comment I sent above. I did `conda deactivate`.

**Comment by efiop** [comment] 2019-04-12 14:48
@odysseus0 I see. Interesting. I'm still unable to reproduce :slightly_frowning_face: Have you tried to `brew update && brew upgrade`?

**Comment by odysseus0** [comment] 2019-04-14 12:23
Yup, I tried `brew update && brew upgrade`. Did not help.

Please let me know what other things you would like to see.

**Comment by shcheklein** [comment] 2019-04-15 18:57
@odysseus0 I was able to reproduce it on my Mac machine either :(. Could you check if it's creating the `/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/target/bin/virtualenv` at all? Could you confirm that you have enough space on `/private/tmp`?

**Comment by odysseus0** [comment] 2019-04-16 01:30
I just checked that `/private/tmp/dvc--homebrew-virtualenv-20190411-16657-1jrg6ad/` is not created at all, or maybe it is automatically deleted after the installation failed? I don't know.

How do I check that I have enough space on `/private/tmp`? I do still have plenty of storage in my laptop.

**Comment by shcheklein** [comment] 2019-04-16 02:02
@odysseus0 okay, can you run something like and include outputs, please:

`brew list` - to see the list of already installed stuff

`brew cleanup -s` to scrub the cache

and `brew doctor` to check if everything looks good?

**Comment by odysseus0** [comment] 2019-04-17 02:13
(base) ➜  ~ brew list
ack			gdk-pixbuf		hub			libheif			libvpx			openexr			rename			vim
aom			gettext			icu4c			libidn2			libyaml			openjpeg		rtmpdump		watch
aws-shell		ghostscript		ilmbase			libmpc			little-cms2		openssl			rubberband		webp
awscli			giflib			imagemagick		libogg			lua			opus			ruby			wget
bash			giflossy		isl			libomp			make			p11-kit			sdl2			x264
cairo			gist			jpeg			libpng			mpfr			pango			shared-mime-info	x265
ctags			git			jq			librsvg			mysql			pcre			snappy			xvid
ffmpeg			git-lfs			lame			libsamplerate		nasm			pcre2			speex			xz
flac			glib			leptonica		libsndfile		ncurses			perl			sqlite
fontconfig		gmp			libass			libsoxr			nettle			pixman			tesseract
freetype		gnutls			libbluray		libtasn1		node			pkg-config		texi2html
frei0r			graphite2		libcroco		libtiff			nvm			proxychains-ng		thefuck
fribidi			harfbuzz		libde265		libtool			oniguruma		python			theora
gcc			highlight		libevent		libunistring		openblas		r			tmux
gdbm			htop			libffi			libvorbis		opencore-amr		readline		unbound
(base) ➜  ~ brew cleanup -s
Removing: /Users/georgezhang/Library/Caches/Homebrew/dvc--0.35.7.tar.gz... (178.5KB)
Removing: /Users/georgezhang/Library/Caches/Homebrew/dvc--homebrew-virtualenv--16.4.3.tar.gz... (3.5MB)
(base) ➜  ~ brew doctor
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry or file an issue; just ignore this. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/georgezhang/anaconda3/bin/icu-config
  /Users/georgezhang/anaconda3/bin/krb5-config
  /Users/georgezhang/anaconda3/bin/freetype-config
  /Users/georgezhang/anaconda3/bin/xslt-config
  /Users/georgezhang/anaconda3/bin/libpng16-config
  /Users/georgezhang/anaconda3/bin/python3.6m-config
  /Users/georgezhang/anaconda3/bin/libpng-config
  /Users/georgezhang/anaconda3/bin/xml2-config
  /Users/georgezhang/anaconda3/bin/python3-config
  /Users/georgezhang/anaconda3/bin/curl-config
  /Users/georgezhang/anaconda3/bin/ncursesw6-config
  /Users/georgezhang/anaconda3/bin/pcre-config
  /Users/georgezhang/anaconda3/bin/python3.6-config

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libnnz11.dylib
  /usr/local/lib/libociei.dylib
  /usr/local/lib/libocijdbc11.dylib

**Comment by shcheklein** [comment] 2019-04-17 05:27
Hmm. Could you share these two files please:

`/Users/georgezhang/Library/Logs/Homebrew/dvc/02.python` and `/Users/georgezhang/Library/Logs/Homebrew/dvc/01.python`

The output should be looking like this:

```
==> python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/dvc--homebrew-virtualenv-20190416-86104-1rs543o/target --install-scripts=/private/tmp/dvc--homebrew-virtualenv-20190416-86104
==> python -s /private/tmp/dvc--homebrew-virtualenv-20190416-86104-1rs543o/target/bin/virtualenv -p python /usr/local/Cellar/dvc/0.35.7/libexec
==> /usr/local/Cellar/dvc/0.35.7/libexec/bin/pip install -r requirements.txt
==> /usr/local/Cellar/dvc/0.35.7/libexec/bin/pip uninstall -y asciimatics
==> /usr/local/Cellar/dvc/0.35.7/libexec/bin/pip uninstall -y Pillow
==> /usr/local/Cellar/dvc/0.35.7/libexec/bin/pip install git+https://github.com/efiop/asciimatics
==> /usr/local/Cellar/dvc/0.35.7/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/dvc-20190416-86104-1jftl7u/dvc-0.35.7
```

It looks like `python -c import setuptools... --no-user-cfg install --prefix=/private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target --install-scripts=/private/tmp/dvc--homebrew-virtualenv-20190417-12488` fails in your case silently. And thus `virtualenv` is not installed.

**Comment by odysseus0** [comment] 2019-04-17 07:13
`/Users/georgezhang/Library/Logs/Homebrew/dvc/02.python`:

----------------------------------

2019-04-17 10:12:09 +0800

python
-s
/private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target/bin/virtualenv
-p
python
/usr/local/Cellar/dvc/0.35.7/libexec

python: can't open file '/private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target/bin/virtualenv': [Errno 2] No such file or directory

HOMEBREW_VERSION: 2.1.0
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: 1337da0f891aebb85accb094d63e401da1b53cba
Last commit: 13 days ago
Core tap ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Core tap HEAD: cee543941686f4daf1fd4b34a3a3204ba23b9c2d
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CACHE: /Users/georgezhang/Library/Caches/Homebrew
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.3.7 => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Clang: 10.0 build 1001
Git: 2.21.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
macOS: 10.14.4-x86_64
CLT: 10.2.0.0.1.1552586384
Xcode: N/A
CLT headers: 10.2.0.0.1.1552586384
XQuartz: 2.7.11 => /opt/X11

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j4
CMAKE_PREFIX_PATH: /usr/local/opt/openssl:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/libxml2:/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.14
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/pkg-config/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/openssl/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python/bin:/usr/bin:/bin:/usr/sbin:/sbin

-------------------------------

`/Users/georgezhang/Library/Logs/Homebrew/dvc/01.python`:

--------------------------------

2019-04-17 10:11:02 +0800

python
-c
import setuptools, tokenize
__file__ = 'setup.py'
exec(compile(getattr(tokenize, 'open', open)(__file__).read()
  .replace('\r\n', '\n'), __file__, 'exec'))
--no-user-cfg
install
--prefix=/private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target
--install-scripts=/private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target/bin
--single-version-externally-managed
--record=installed.txt

warning: no previously-included files found matching 'pyproject.toml'

Installed /private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/virtualenv-16.4.3/.eggs/setuptools-41.0.0-py2.7.egg
running install
running build
running build_py
creating build
creating build/lib
copying virtualenv.py -> build/lib
running install_lib
copying build/lib/virtualenv.py -> /private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target/lib/python2.7/site-packages
byte-compiling /private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target/lib/python2.7/site-packages/virtualenv.py to virtualenv.pyc
running install_egg_info
running egg_info
creating UNKNOWN.egg-info
writing UNKNOWN.egg-info/PKG-INFO
writing top-level names to UNKNOWN.egg-info/top_level.txt
writing dependency_links to UNKNOWN.egg-info/dependency_links.txt
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
warning: manifest_maker: standard file '-c' not found

reading manifest file 'UNKNOWN.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching 'readthedocs.yml'
warning: no previously-included files found matching 'CONTRIBUTING.rst'
warning: no previously-included files found matching '.pre-commit-config.yaml'
warning: no previously-included files found matching 'azure-run-tox-env.yml'
warning: no previously-included files found matching 'azure-pipelines.yml'
warning: no previously-included files found matching '.gitignore'
warning: no previously-included files found matching '.gitattributes'
warning: no previously-included files matching '*' found under directory '.github'
writing manifest file 'UNKNOWN.egg-info/SOURCES.txt'
Copying UNKNOWN.egg-info to /private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/target/lib/python2.7/site-packages/UNKNOWN-16.4.3-py2.7.egg-info
running install_scripts
writing list of installed files to 'installed.txt'

**Comment by shcheklein** [comment] 2019-04-17 08:37
I'm wondering if we should ask Homebrew guys to help with this at this stage.

@odysseus0 there are a few strange things:

```warning: no previously-included files found matching 'pyproject.toml'

Installed /private/tmp/dvc--homebrew-virtualenv-20190417-12488-107j4nf/virtualenv-16.4.3/.eggs/setuptools-41.0.0-py2.7.egg```

what does your `pip list` return?

and second thing is "UNKNOWN.egg-info/" - have no idea what is this about so far.

**Comment by odysseus0** [comment] 2019-04-18 02:45
`pip install dvc` works perfectly fine for me. I also tried uninstall `dvc` from `pip` and then try homebrew install again, but still no luck for me.

For now, I will just use `pip install dvc` as it is perfectly functional and cross-platform.

**Comment by shcheklein** [comment] 2019-04-18 05:05
@odysseus0 you can also you install it via `.pkg` - `https://github.com/iterative/dvc/releases`, btw. I'm going to close it since it looks like it's something very specific to the environment and we have a workaround.

**Closed by shcheklein** 2019-04-18 05:05 UTC
